name: $(BuildID)

trigger: 
  branches:
    include: [ main, d16-*, d17-* ]
pr:
  autoCancel: 'true'
  branches:
    include: [ main, d16-*, d17-* ]

resources:
  repositories:
  - repository: self
  - repository: templates   # for shared yaml templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/main
    endpoint: xamarin

# Variables
variables:
- template: .build/automation/variables.yml

stages:
  - template: .build/automation/stages/validate.yml
  - template: .build/automation/stages/security_compliance.yml
  - template: .build/automation/stages/localization-handoff.yml                     # Process outgoing strings [Localization Handoff]
  - template: .build/automation/stages/localization-handback.yml                    # Process incoming translations and Create PR to main [Localization Handback]
  - template: .build/automation/stages/merge-translations-update.yml                # Validating incoming translations strings and merge PR [Localization Handback]
